PUT http://localhost:8080/events/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTc3NTA3NzQyMCwidXNlcklkIjoyfQ.ze5pI1BuIKTk6RZlZVBs1KiY1FE5WykXjj2z0YIMG8I

{
    "name": "Test",
    "description": "This is text event",
    "location": "burco"
}